<?php

namespace AppBundle\Repository;

/**
 * ShopifyCheckoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopifyCheckoutRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestUpdateDate(){
        $query = $this->createQueryBuilder('s');
        $query->select('MAX(s.updatedAt) AS latest_updated_date');
        return $query->getQuery()->getSingleResult();

    }
}
