<?php

namespace AppBundle\Repository;

/**
 * ShopifyOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopifyOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestUpdateDate($shopId){
        $query = $this->createQueryBuilder('s');
        $query->select('MAX(s.updatedAt) AS latest_updated_date')
            ->where('s.shop = :shop')
            ->setParameter('shop',$shopId)
        ;
        return $query->getQuery()->getSingleResult();

    }
}
